@startuml
actor       User        as Foo
Foo -> "~#userNameInput: TextField": write name
"~#userNameInput: TextField" <- PacManController: getText

PacManController-> PacMan: updateGui
Foo -> "~#handleStartButton": click

PacManController <- "~#handleStartButton": handleStartButton
PacManController -> PacMan: setUserName

Foo -> PacManApp: arrowkeys
PacManApp -> PacMan: changeDirection

PacManController -> PacManController: gameOver
PacManController -> PacManPersistance: saveHighscore
PacManPersistance -> PacMan: getUsername, getScore

PacManController -> PacManPersistance: fetchScoreBoard
PacManController -> "~#highscores: TextArea" : setText

Foo -> "~#handleRestartGameButton": click
"~#handleRestartGameButton" -> PacManController: handleRestartGameButton

@enduml